title: CS Conference Deadlines 
# email: 
description: Countdowns to top DM/DB/IR/NLP/AI/ML/SE conference deadlines
author: Hui Li


domain: ""
baseurl: ""

# twitter_username:
# twitter_hashtag: 
# github_username: 
# github_repo: 

markdown: kramdown
# ga_id:

include: ['_pages']